In [1]:
# I want to Start the journey for Python libraries

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [4]:
#we have to check numpy version
print(np.__version__)

2.1.3


In [5]:
# Create a 2D Array
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [7]:
#Generate an Array of Zeros
zeros=np.zeros((4,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Generate an arrays of ones
ones=np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [10]:
#Create an Array with Range
range_=np.arange(10)
print(range_)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
#Create Evenely Spaced Numbers
linspace_arr=np.linspace(0,1,5)
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


In [17]:
#Check Shape and Datatype
print(arr.shape)
print(arr.dtype)

(9,)
int64


In [18]:
# Convert List to Numpy Array and Check Type
list1=[10,20,30]
array_lis=np.array(list1)
print(type(list1))
print(array_lis)

<class 'list'>
[10 20 30]
