In [ ]:
candidate1=input("Enter 1st candidate name:")
candidate2=input("Enter 2nd candidate name:")
cand1_votes=0
cand2_votes=0
voters_id=[1,2,3,4,5,6,7,8,9]
voted=[]
while True:
    if voters_id==[]:
        print("voting is over")
        if candidate1>candidate2:
            print(f"{candidate1} Won the election with {cand1_votes}")
        elif candidate2>candidate1:
            print(f"{candidate2} Won the election with {cand2_votes}")
        elif candidate1==candidate2:
            print("Tied")
        break
    else:
        voter=int(input("Enter your id"))
        if voter in voted:
            print("you allready voted")
            
        else:
            if voter in voters_id:
                print(f"1.{candidate1}\n2.{candidate2}")
                choice=int(input("Enter your choice"))
                if choice == 1:
                    cand1_votes+=1
                    print(f"You voted {candidate1}")
                elif choice ==2:
                    cand2_votes+=1
                    print(f"You voted {candidate2}")
                voters_id.remove(voter)
                voted.append(voted)
            else:
                print("You are not allowed to vote")
        
        

Enter 1st candidate name: Manisha
Enter 2nd candidate name: Kalyani
Enter your id 1


1.Manisha
2.Kalyani


Enter your choice 1


You voted Manisha


In [ ]:
# Get candidate names
candidate1 = input("Enter 1st candidate name: ")
candidate2 = input("Enter 2nd candidate name: ")

# Initialize vote counts
cand1_votes = 0
cand2_votes = 0

# Registered voters and those who already voted
voters_id = [1, 2, 3, 4, 5, 6, 7, 8, 9]
voted = []

# Voting loop
while True:
    if not voters_id:
        print("\nVoting is over.")
        print(f"\nFinal Results:\n{candidate1}: {cand1_votes} votes\n{candidate2}: {cand2_votes} votes")

        if cand1_votes > cand2_votes:
            print(f"\n{candidate1} won the election!")
        elif cand2_votes > cand1_votes:
            print(f"\n{candidate2} won the election!")
        else:
            print("\nThe election ended in a tie.")
        break

    try:
        voter = int(input("\nEnter your voter ID: "))
    except ValueError:
        print("Invalid input. Please enter a numeric voter ID.")
        continue

    if voter in voted:
        print("You have already voted.")
    elif voter in voters_id:
        print(f"\nPlease cast your vote:\n1. {candidate1}\n2. {candidate2}")
        try:
            choice = int(input("Enter your choice (1 or 2): "))
        except ValueError:
            print("Invalid input. Please enter 1 or 2.")
            continue

        if choice == 1:
            cand1_votes += 1
            print(f"You voted for {candidate1}")
        elif choice == 2:
            cand2_votes += 1
            print(f"You voted for {candidate2}")
        else:
            print("Invalid choice. Please select 1 or 2.")
            continue

        voted.append(voter)
        voters_id.remove(voter)
    else:
        print("You are not allowed to vote or invalid voter ID.")


Enter 1st candidate name:  monty bhai
Enter 2nd candidate name:  aditya bhai

Enter your voter ID:  1



Please cast your vote:
1. monty bhai
2. aditya bhai


Enter your choice (1 or 2):  1


You voted for monty bhai



Enter your voter ID:  2



Please cast your vote:
1. monty bhai
2. aditya bhai


Enter your choice (1 or 2):  1


You voted for monty bhai



Enter your voter ID:  10


You are not allowed to vote or invalid voter ID.


In [2]:
import numpy as np


In [3]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a2=a*2
a2


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
total=np.sum(a)
print(total)


55


In [5]:
mean=np.mean(a)
print(mean)

5.5


In [6]:
std=np.std(a)
print(std)

2.8722813232690143


In [7]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

shape=arr.shape
transpose=arr.T
element_2_3=arr[1,2]
row_sum=np.sum(arr, axis=1)
col_sum=np.sum(arr, axis=0)
print(shape)
print(transpose)
print(element_2_3)
print(row_sum)
print(col_sum)
     

(3, 3)
[[1 4 7]
 [2 5 8]
 [3 6 9]]
6
[ 6 15 24]
[12 15 18]


In [8]:
# we have to perform min max for using normalization method 
scores=([45,60,72,88,95])
min_val=np.min(scores)
max_val=np.max(scores)
normalize_scores=(scores-min_val)/(max_val-min_val)
print(f"minimum value:",min_val)
print(f"maximum value:",max_val)
print(normalize_scores)

minimum value: 45
maximum value: 95
[0.   0.3  0.54 0.86 1.  ]


In [9]:
#we have to solve standardized method this is also known as z score normalization 
score=([25,35,45,56,67,78])
mean=np.mean(score)
std_dev=np.std(score)
standardization=score-mean/std_dev
print(score)
print(mean)
print(std_dev)
print(standardization)

[25, 35, 45, 56, 67, 78]
51.0
18.15672510852843
[22.19112342 32.19112342 42.19112342 53.19112342 64.19112342 75.19112342]


In [10]:
arr=np.arange(1,13)

In [12]:
re_shape=arr.reshape(3,4)

In [13]:
print(arr)
print(re_shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
arr=np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])


In [24]:
print(arr[0])
print(arr[1,1])
print(arr[:,2])

[10 20 30]
50
[30 60 90]


In [27]:
arr=np.array([5,12,7,9,21,17])
greater=arr[arr>10]
odd=arr[arr%2!=0]
print(arr)
print(greater)
print(odd)

[ 5 12  7  9 21 17]
[12 21 17]
[ 5  7  9 21 17]


In [28]:
a=np.array([2,4,6])
b=np.array([1,3,5])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)


[ 3  7 11]
[1 1 1]
[ 2 12 30]
[2.         1.33333333 1.2       ]
[ 4 16 36]


In [29]:
data = np.array([15, 22, 8, 19, 31, 25])
mean=np.mean(data)
median=np.median(data)
min_=np.min(data)
max_=np.max(data)
std=np.std(data)
var=np.var(data)
print(mean)
print(median)
print(min_)
print(max_)
print(std)
print(var)

20.0
20.5
8
31
7.302967433402215
53.333333333333336


In [30]:
# we are using pandas libraris
import pandas as pd

In [33]:
data={'Name':['Yash','Aditya','Monty'],
      'Age':[23,24,26],
      'City':['Nashik','Pune','Delhi']}
df=pd.DataFrame(data)
print(df)

     Name  Age    City
0    Yash   23  Nashik
1  Aditya   24    Pune
2   Monty   26   Delhi


In [40]:
# Select a column
df['Name']
# Select multiple columns
df[['Name', 'City']]

# Select row by index label
df.loc[1]     # Row for Bob
# Select row by index position
df.iloc[2]    # Row for Charlie





Name    Monty
Age        26
City    Delhi
Name: 2, dtype: object

In [41]:
# Add column
df['Score'] = [85, 90, 88]

# Remove column
df.drop('City', axis=1, inplace=True)

print(df)


     Name  Age  Score
0    Yash   23     85
1  Aditya   24     90
2   Monty   26     88


In [42]:
# Filter: Age > 23
filtered = df[df['Age'] > 23]
print(filtered)


     Name  Age  Score
1  Aditya   24     90
2   Monty   26     88


In [45]:
#loop Problem

In [63]:
nums=[1,2,3,4,5,6,7,8,9]
even=0
odd=0
for num in nums:
    if num%2==0:
        even+=1
    else:
        odd+=1
print(f"Even:{even},Odd:{odd}")

Even:4,Odd:5


In [49]:
even = 0
odd = 0

for num in nums:
    if num % 2 == 0:
        even += 1
    else:
        odd += 1

print(f"Even: {even}, Odd: {odd}")


Even: 4, Odd: 5


In [61]:

even_number=[]
odd_number=[]
for i in range(1,11):
    if i%2==0:
        even_number.append(i)
    else:
        odd_number.append(i)
print(even_number)
print(odd_number)

    
        

[2, 4, 6, 8, 10]
[1, 3, 5, 7, 9]


In [70]:
#2️⃣ Problem: Print Multiples of 3 or 5 from 1 to 50
for i in range(1,51):
    if i%3==0 or i%5==0:
        print(i,end=" ")

3 5 6 9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 

In [71]:
for i in range(1, 51):
    if i % 3 == 0 and i % 5 == 0:
        print(i, end=' ')


15 30 45 

In [73]:
#3️⃣ Problem: FizzBuzz fizzbuzz means if num is divisible by 3 then print fizz or divisible by 5 print buzz and divide by 3and 5 then print fizzbuzz
for i in range(1,21):
    if i%3==0:
        print("fizz")
    elif i%5==0:
        print("buzz")
    elif i%3==0 and i%5==0:
        print("fizzbuzz")
    else:
        print(i)
    

1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizz
16
17
fizz
19
buzz


In [74]:
for i in range(1, 21):
    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz")
    elif i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
        print("Buzz")
    else:
        print(i)


1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz


In [4]:
#4️⃣ Problem: Find Prime Numbers from 1 to 50
for num in range(2,51):
    is_prime=True
    for i in range(2,int(num**0.5)+1):
        if num%i==0:
            is_prime=False
            break
    if is_prime:
        print(num,end=" ")
    
    

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 

In [83]:
a=[1,2,3,4]
b=a[::-1]
print(b)

[4, 3, 2, 1]


In [91]:
a=1234
reverse=str(a)[::-1]
b=int(reverse)
b

4321

In [103]:
#without using slicing method
def reverse_string(num):
    result=""
    for i in str(num):
        result=i+result
    return result
num = 1234
print(reverse_string(num))

4321


In [105]:
#palindrome method in that 121 is the panlidrome there first and last term are same
def is_palindrome(num):
    return str(num)==str(num)[::-1]
print(is_palindrome(121))
print(is_palindrome(123))

True
False


In [113]:
#sum of digit of number with loop method
def a(num):
    total=0
    for digit in str(num):
        total+=int(digit)
    return total
print(a(9102903))

24


In [114]:
#this method without using loop and condition method
def sum_of_digits(num):
    return sum(map(int, str(num)))

# Test
print(sum_of_digits(1234))  # Output: 10


10


In [117]:
#we count the vowels in letter 
def count_vowels(s):
    vowels="aeiouAEIOU"
    count=0
    for char in s:
        if char in vowels:
            count=+1
    return count
print(count_vowels('Hello'))


1


In [126]:
#find Largest value in list its have teo method 1 is using loop and 2 is without using loop we see both method
def find_largest(nums):
    largest=nums[0]
    for num in nums:
        if num>largest:
            largest=num
    return largest
print(find_largest([1,2,3,4,5,6,7,8]))

8


In [127]:
list1=[1,2,3,4,5,6,7,8]
print(max(list1))

8


In [141]:
def print_pattern(n):
    for i in range(1,n+1):
        print(' * '* i)
print_pattern(6)

 * 
 *  * 
 *  *  * 
 *  *  *  * 
 *  *  *  *  * 
 *  *  *  *  *  * 


In [163]:
#without using def method 
for i in range (n):
    for j in range (i+1):
        print('*',end=' ')
    print()

* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 


In [146]:
n=6
for i in range(n):
    for j in range(i,n):
        print('*',end=' ')
    print()

* * * * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


In [148]:
n=6
for i in range(n):
    for j in range(i,n):
        print(' ',end=' ')
    for j in range(i+1):
        print('*',end=' ')
    print()

            * 
          * * 
        * * * 
      * * * * 
    * * * * * 
  * * * * * * 


In [149]:
n=6
for i in range(n):
    for j in range(1+i):
        print(' ',end=' ')
    for j in range(i,n):
        print('*',end=' ')
    print()

  * * * * * * 
    * * * * * 
      * * * * 
        * * * 
          * * 
            * 


In [151]:
n=6
for i in range(n):
    for j in range(i,n):
        print(' ',end=' ')
    for j in range(i):
        print('*',end=' ')
    for j in range(i+1):
        print('*',end=' ')
    print()
        

            * 
          * * * 
        * * * * * 
      * * * * * * * 
    * * * * * * * * * 
  * * * * * * * * * * * 


In [161]:
def print_reverse_triangle(n):
    for i in range(n):
        for j in range(i, n):
            print('*', end=' ')
        print()

# Call the function
print_reverse_triangle(6)


* * * * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


In [171]:
#need to find an factorial number
num=5
fact=1
for i in range(1,num+1):
    fact=fact*i
print("Factorial:",fact)

Factorial: 120


In [167]:
n = 5
fact = 1
for i in range(1, n + 1):
    fact *= i
print("Factorial:", fact)


Factorial: 120


In [1]:
n = 5
fact = 1
for i in range(1, n + 1):
    fact *= i
print("Factorial:", fact)

Factorial: 120


In [2]:
n = 10
a, b = 0, 1
for _ in range(n):
    print(a, end=' ')
    a, b = b, a + b


0 1 1 2 3 5 8 13 21 34 

In [3]:
num = 12345
count = 0
while num > 0:
    count += 1
    num //= 10
print("Digits:", count)


Digits: 5


In [5]:
def reverse_string(n):
    total=""
    for i in str(n):
        total=i+total
    return total
print(reverse_string(1234))

4321


In [12]:
def a(num):
    total=0
    for i in str(num):
        total=total+int(i)
    return total
print(a(123456677))

41


In [24]:
#✅ 11. Check if a number is prime
n=300
is_prime=True
if num<2:
    is_prime=False
else:
    for i in range (2,int(num**0.5)+ 1):
        if num%i==0:
            is_prime=False
            break
print("Prime" if is_prime else "Not prime")


Not prime


In [7]:
for num in range(2,101):
    is_prime=True
    for i in range(2,int(num**0.5)+1):
        if num%i==0:
            is_prime=False
            break
    if is_prime:
        print(num,end=',')

2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,

In [6]:
#✅ 12. Print all prime numbers in a range
for num in range (10,51):
    is_prime=True
    for i in range(2,int(num**0.5)+1):
        if num%i==0:
            is_prime=False
            break
    if is_prime:
        print(num,end=' ')

11 13 17 19 23 29 31 37 41 43 47 

In [8]:
#armstrong method using for loop method
num=153
order=len(str(num))
total=0
for digit in str(num):
    total=total+int(digit)**order
if total==num:
    print("Armstrong")
else:
    print("Not Armstrong")

Armstrong


In [9]:
#armstong method using while loop condition
num=int(input("Enter any Number"))
sum=0
cnum=num
while (num>0):
    rem=num%10
    sum=sum+rem**3
    num=num//10
print(sum)
print(num)
print(cnum)
if cnum==sum:
    print("Armstrong")
else:
    print("Not Armstrong")

Enter any Number 153


153
0
153
Armstrong


In [11]:
# we find out the lcm from the given digit by while loop and for loop
#first while loop
a,b=12,18
lcm=max(a,b)
while True:
    if lcm%a==0 and lcm%b==0:
        print(lcm)
        break
    lcm+=1

36


In [15]:
#for method
a,b=12,18
for lcm in range(max(a,b),(a*b)+1):
    if lcm%a==0 and lcm%b==0:
        print(lcm)
        break

36


In [18]:
for i in range (1,11):
    if i%2==0:
        print(i)
    

2
4
6
8
10


In [20]:
num=int(input("enter any number"))
if i%2==0:
    print("Even")
else:
    print("odd")

enter any number 2


Even


In [21]:
for i in range(1, 11):
    if i % 2 == 0:
        print(f"{i} is Even")
    else:
        print(f"{i} is Odd")


1 is Odd
2 is Even
3 is Odd
4 is Even
5 is Odd
6 is Even
7 is Odd
8 is Even
9 is Odd
10 is Even


In [30]:
def sum_digit(s):
    total=0
    for i in str(s):
        total=total+int(i)
    return total
print(sum_digit(1234))


10


In [35]:
def is_palindrome(num):
    return str(num)==str(num)[::-1]
print(is_palindrome(122))
print(is_palindrome(121))

False
True


In [37]:
num=int(input("Enter any Number"))
sum=0
cnum=num
while (num>0):
    rem=num%10
    sum=sum+rem**3
    num=num//10
print(rem)
print(sum)
print(cnum)
if cnum==sum:
    print("Armstrong")
else:
    print("Not Armstrong")


Enter any Number 153


1
153
153
Armstrong


In [47]:
num=153
order=len(str(num))
total=0
for i in str(num):
    total=total+int(i)**order
if total==num:
    print("armstrong")
else:
    print("not armstrong")

armstrong


In [48]:
def is_armstrong(num):
    order=len(str(num))
    total=0
    for i in str(num):
        total=total+int(i)**order
    return total==num

print(is_armstrong(153))

True


In [57]:
def pyramid(n):
    num=1
    for i in range(1,n+1):
        for j in range(i):
            print(num,end=' ')
            num+=1
        print()
pyramid(5)
    
            

1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 


In [57]:
def pyramid(n):
    num=1
    for i in range(1,n+1):
        for j in range(i):
            print(num,end=' ')
            num+=1
        print()
pyramid(5)
    
            

1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 


In [59]:
for i in range(1,20):
    if i%3==0 and i%5==0:
        print("FizzBuzz")
    elif i%3==0:
        print("Fizz")
    elif i%5==0:
        print("Buzz")
    else:
        print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19


In [61]:
num=123456
count=len(str(num))
count

6

In [73]:
n=5
for i in range(1,n+1):
    for j in range(1,i+1):
        print(j,end=' ')
    print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [77]:
#Fibonacci concept
def fibonacci_iterative(n):
    a,b=0,1
    for i in range(n):
        a,b=b,a+b
    return a
print(fibonacci_iterative(20))

6765


In [80]:
def fibonacci_series(n):
    a, b = 0, 1
    print("Fibonacci Series:")
    for i in range(n):
        print(a, end=' ')
        a, b = b, a + b

# Test
fibonacci_series(20)


Fibonacci Series:
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 

In [84]:
def fibonacci_series(n):
    total=0
    a, b = 0, 1
    print("Fibonacci Series:")
    for i in range(n):
        total+=a
        a, b = b, a + b
    return total
print(fibonacci_series(10))

Fibonacci Series:
88
