In [1]:
import numpy


In [2]:
import numpy as np


In [4]:
arr1=np.array([11,22,33,44,55])
arr1
arr2=np.array(['Female','male','female','male'])
arr2


array(['Female', 'male', 'female', 'male'], dtype='<U6')

In [5]:
arr2=np.array(['Female','male','female','male'])
arr2

array(['Female', 'male', 'female', 'male'], dtype='<U6')

In [12]:
l1=[111,222,333,444,555]
l2=[1,2,3,4,5]
array1=np.array([l1,l2])
array1
type(array1)


numpy.ndarray

In [7]:
my_list=[1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [13]:
type(array1)

numpy.ndarray

In [14]:
array1.ndim   #return number of dimension in the array

2

In [15]:
array1.size

10

In [17]:
array1.shape

(2, 5)

In [22]:
matrix_array=[[[1,2,3,4]],[[5,6,7,8]],[[9,10,11,12]]]
matrix_array=np.array(matrix_array)
matrix_array

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [23]:
matrix_array.ndim

3

In [25]:
print('The Dimension of array',matrix_array.ndim)

The Dimension of array 3


In [27]:
arr1=np.array([[[1,2,3,4]],[[5,6,7,8]],[[9,10,11,12]]])
arr1
arr1.shape

(3, 1, 4)

In [28]:
#arr2=arr1.reshape(-1)

In [29]:
arr2.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [30]:
arr1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
arr1.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [42]:
arr1.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [44]:
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [48]:
#zeros function

In [49]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
np.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [52]:
#linspace

In [53]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [54]:
#eye

In [55]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
np.full(10,10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [59]:
np.full(5,10)

array([10, 10, 10, 10, 10])